# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 18:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('chart_of_accounts', '0001_initial'),
        ('vendor', '0002_auto_20170906_1444'),
        ('transactions', '0001_initial'),
        ('inventory', '0001_initial'),
        ('purchase_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=10)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Bill_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill_currency', to='organizations.OrgCurrencies')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bill_modified_by', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill_org_id', to='organizations.Organization')),
                ('po_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bill_po_number', to='purchase_order.PurchaseOrder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_vendor', to='vendor.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_bill', to='bill.Bill')),
                ('cr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_cr_account', to='chart_of_accounts.ChartOfAccount')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_created_by', to=settings.AUTH_USER_MODEL)),
                ('dr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_dr_account', to='chart_of_accounts.ChartOfAccount')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_item', to='inventory.Inventory')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_modified_by', to=settings.AUTH_USER_MODEL)),
                ('trnx_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_trnx_number', to='transactions.Transaction')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set([('org_id', 'bill_no')]),
        ),
    ]
