# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetails',
            name='trnx_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_trnx_number', to='transactions.Transaction'),
        ),
    ]
