# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
