# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_auto_20170916_1110'),
        ('bill', '0002_auto_20170911_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.Tax'),
        ),
    ]
