# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_billdetails_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetails',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BillDetails_tax', to='tax.Tax'),
        ),
    ]
