# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_auto_20170917_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amounts_are',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bill_amounts_are_LOV', to='AccountingApp.LOV'),
        ),
    ]
