# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20170917_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
