# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_auto_20170917_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='tax_amount',
            new_name='total_tax_amount',
        ),
        migrations.AddField(
            model_name='billdetails',
            name='tax_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30),
        ),
    ]
