# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20170815_2219'),
        ('AccountTypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttypes',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='accounttypes',
            unique_together=set([('org_id', 'name'), ('org_id', 'code')]),
        ),
    ]
