# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountTypes', '0002_auto_20170817_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttypes',
            name='main_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='orgID', to='AccountTypes.AccountTypes'),
        ),
    ]
