# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 20:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountingApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='organization_created_by', to=settings.AUTH_USER_MODEL)),
                ('main_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_main_org', to='organizations.Organization')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_modified_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrganizationMember_organization_id', to='organizations.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationMember_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_precision', models.IntegerField(default=2)),
                ('base_currency', models.BooleanField(default=False)),
                ('Org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgCurrencies_org_id', to='organizations.Organization')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgCurrencies_currency_id', to='AccountingApp.Currencies')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orgcurrencies',
            unique_together=set([('Org_id', 'currency_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together=set([('organization_id', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('owner', 'name')]),
        ),
    ]
