# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 23:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AccountingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_user_first_name', models.CharField(max_length=100)),
                ('invited_user_last_name', models.CharField(max_length=100)),
                ('invited_user_email', models.EmailField(max_length=254)),
                ('invited_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invitation_url', models.URLField()),
                ('invitation_sent', models.BooleanField(default=False)),
                ('invitation_accepted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='organization_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_modified_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='organization_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('invitation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationMember_invitation_id', to='organizations.InvitedUsers')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OrganizationMember_organization_id', to='organizations.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationMember_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_precision', models.IntegerField(default=2)),
                ('base_currency', models.BooleanField(default=False)),
                ('Org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgCurrencies_org_id', to='organizations.Organization')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgCurrencies_currency_id', to='AccountingApp.Currencies')),
            ],
        ),
        migrations.CreateModel(
            name='OrgExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapped_current_rate', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('override_rate', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('Org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_Org_id', to='organizations.Organization')),
                ('ex_rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_ex_rate_id', to='AccountingApp.ExchangeRate')),
                ('from_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_from_currency_id', to='organizations.OrgCurrencies')),
                ('related_OrgCurrencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_related_curr_id', to='organizations.OrgCurrencies')),
                ('to_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_to_currency_id', to='organizations.OrgCurrencies')),
            ],
        ),
        migrations.AddField(
            model_name='invitedusers',
            name='invite_to_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users_user_to_org', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='invitedusers',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_users_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitedusers',
            name='inviter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_users_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='orgexchangerate',
            unique_together=set([('Org_id', 'related_OrgCurrencies')]),
        ),
        migrations.AlterUniqueTogether(
            name='orgcurrencies',
            unique_together=set([('Org_id', 'currency_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together=set([('organization_id', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('owner', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='invitedusers',
            unique_together=set([('invite_to_org', 'invited_user_email')]),
        ),
    ]
