# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20170813_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='updated_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
