# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0002_remove_currencies_base_currency'),
        ('organizations', '0002_auto_20170823_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgexchangerate',
            name='ex_rate_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_ex_rate_id', to='AccountingApp.ExchangeRate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgexchangerate',
            name='swapped_current_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='orgexchangerate',
            name='from_currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_from_currency_id', to='AccountingApp.Currencies'),
        ),
        migrations.AlterField(
            model_name='orgexchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 20, 54, 16, 572650, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orgexchangerate',
            name='to_currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_to_currency_id', to='AccountingApp.Currencies'),
        ),
    ]
