# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20170823_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgexchangerate',
            name='from_currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_from_currency_id', to='organizations.OrgCurrencies'),
        ),
        migrations.AlterField(
            model_name='orgexchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 10, 53, 46, 964493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orgexchangerate',
            name='to_currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrgExchangeRate_to_currency_id', to='organizations.OrgCurrencies'),
        ),
    ]
