# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20170824_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgexchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 15, 43, 26, 214529, tzinfo=utc)),
        ),
    ]
