# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20170824_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgexchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 18, 31, 32, 43441, tzinfo=utc)),
        ),
    ]
