# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20170824_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgexchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 21, 16, 54, 277932, tzinfo=utc)),
        ),
    ]
