# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 13:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('main_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingApp.AccountTypes')),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('main_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountingApp.ChartOfAccounts')),
                ('type_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingApp.AccountTypes')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=500)),
                ('message', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('decimal_precision', models.IntegerField(default=2)),
                ('currency_latin_name', models.CharField(max_length=500)),
                ('currency_arabic_name', models.CharField(max_length=500)),
                ('base_currency', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DrCr',
            fields=[
                ('dr_cr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dr_cr_desc', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('exchange_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=30)),
                ('override_rate', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2017, 7, 30, 16, 49, 54, 730303))),
                ('from_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency_id', to='AccountingApp.Currencies')),
                ('to_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency_id', to='AccountingApp.Currencies')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([('from_currency_id', 'to_currency_id')]),
        ),
    ]
