# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='base_currency',
        ),
    ]
