# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime(2017, 7, 30, 16, 51, 13, 901670))),
                ('value_date', models.DateTimeField(default=datetime.datetime(2017, 7, 30, 16, 51, 13, 901670))),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=30)),
                ('base_eqv_amount', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('base_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_base_currency_id', to='AccountingApp.Currencies')),
                ('cr_account_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_cr_account_code', to='AccountingApp.ChartOfAccounts')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_currency_id', to='AccountingApp.Currencies')),
                ('dr_account_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_dr_account_code', to='AccountingApp.ChartOfAccounts')),
            ],
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 16, 51, 13, 902670)),
        ),
    ]
