# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=10)),
                ('l_value', models.CharField(max_length=10)),
                ('a_value', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lov',
            unique_together=set([('domain', 'l_value')]),
        ),
    ]
