# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0002_remove_currencies_base_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('value_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=30)),
                ('base_eqv_amount', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('narrative', models.CharField(blank=True, max_length=500, null=True)),
                ('base_currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_base_currency_id', to='AccountingApp.Currencies')),
                ('cr_account_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_cr_account_code', to='AccountingApp.ChartOfAccounts')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_currency_id', to='AccountingApp.Currencies')),
                ('dr_account_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transactions_dr_account_code', to='AccountingApp.ChartOfAccounts')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('source_key', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='base_currency_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='cr_account_code',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='dr_account_code',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
