# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0002_auto_20170802_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 7, 18, 40, 837418)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 7, 18, 40, 834707)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 2, 7, 18, 40, 834775)),
        ),
    ]
