# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0002_auto_20170917_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lov',
            name='a_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lov',
            name='domain',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lov',
            name='l_value',
            field=models.CharField(max_length=50),
        ),
    ]
