# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0002_auto_20170730_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypesDrCr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingApp.AccountTypes')),
                ('dr_cr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingApp.DrCr')),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('sign', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 7, 38, 411658)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 7, 38, 410658)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 7, 38, 410658)),
        ),
        migrations.AddField(
            model_name='accounttypesdrcr',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountingApp.Sign'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttypesdrcr',
            unique_together=set([('code', 'dr_cr')]),
        ),
    ]
