# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0003_auto_20170826_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactions',
        ),
    ]
