# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0003_auto_20170730_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 55, 28, 359080)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 55, 28, 358079)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 55, 28, 358079)),
        ),
    ]
