# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0003_auto_20170802_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 13, 30, 34, 371655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 13, 30, 34, 370655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 13, 30, 34, 370655, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
