# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0004_auto_20170730_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='narrative',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 0, 42, 17, 443705)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 0, 42, 17, 441705)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 0, 42, 17, 441705)),
        ),
    ]
