# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0004_auto_20170820_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 19, 7, 9, 913774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 19, 7, 9, 912774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 19, 7, 9, 912774, tzinfo=utc)),
        ),
    ]
