# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0004_auto_20170826_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsources',
            name='source_key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
