# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0005_auto_20170731_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 0, 43, 46, 711810)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='narrative',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 0, 43, 46, 708810)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 0, 43, 46, 708810)),
        ),
    ]
