# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 12:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountingApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('ordered_qty', models.IntegerField(default=0)),
                ('sold_qty', models.IntegerField(default=0)),
                ('canceled_qty', models.IntegerField(default=0)),
                ('avg_cost', models.DecimalField(decimal_places=6, max_digits=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_currency', to='AccountingApp.Currencies')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_modified_by', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inventory_org_id', to='organizations.Organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('org_id', 'item_id')]),
        ),
    ]
