# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_auto_20170920_0107'),
        ('transactions', '0002_auto_20170920_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_tax', to='tax.Tax'),
        ),
    ]
