# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20170920_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tax',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_tax', to='tax.Tax'),
            preserve_default=False,
        ),
    ]
