# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 20:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(max_length=10)),
                ('total_tax_pct', models.DecimalField(decimal_places=4, default=0, max_digits=4, max_length=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='Tax_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tax_modified_by', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tax_org_id', to='organizations.Organization')),
                ('tax_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tax_tax_account', to='chart_of_accounts.ChartOfAccount')),
            ],
        ),
        migrations.CreateModel(
            name='TaxComponents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_desc', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=4, max_length=4)),
                ('compound', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='TaxComponents_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TaxComponents_modified_by', to=settings.AUTH_USER_MODEL)),
                ('tax_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaxComponents_tax', to='tax.Tax')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taxcomponents',
            unique_together=set([('tax_id', 'id')]),
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together=set([('org_id', 'tax_id')]),
        ),
    ]
