# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_desc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
