# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_tax_tax_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcomponents',
            name='percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
