# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_auto_20170916_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcomponents',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
