# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20170815_2219'),
        ('AccountTypes', '0003_auto_20170818_1827'),
        ('chart_of_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='main_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChartOfAccounts_main_code', to='chart_of_accounts.ChartOfAccounts'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChartOfAccounts_org_id', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChartOfAccounts_type_code', to='AccountTypes.AccountTypes'),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccounts',
            unique_together=set([('org_id', 'type_code', 'code'), ('org_id', 'type_code', 'name')]),
        ),
    ]
